ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-35' coro=<create_search_interface.<locals>.update_connection_status() done, defined at /Users/mukhiyas/Library/CloudStorage/OneDrive-moodys.com/Desktop/gr5-master/main.py:9023> exception=AttributeError("can't set attribute")>
Traceback (most recent call last):
  File "/Users/mukhiyas/Library/CloudStorage/OneDrive-moodys.com/Desktop/gr5-master/main.py", line 9029, in update_connection_status
    connection_status.classes = 'text-xs text-green-600 mt-2'
AttributeError: can't set attribute
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-89' coro=<create_search_interface.<locals>.update_connection_status() done, defined at /Users/mukhiyas/Library/CloudStorage/OneDrive-moodys.com/Desktop/gr5-master/main.py:9023> exception=AttributeError("can't set attribute")>
Traceback (most recent call last):
  File "/Users/mukhiyas/Library/CloudStorage/OneDrive-moodys.com/Desktop/gr5-master/main.py", line 9029, in update_connection_status
    connection_status.classes = 'text-xs text-green-600 mt-2'
AttributeError: can't set attribute
INFO:databricks.sql.auth.retry:Received status code 200 for POST request
INFO:databricks.sql.auth.thrift_http_client:HTTP Response with status code 200, message: OK
INFO:databricks.sql.client:Successfully opened session 01f0881e-81ba-15b8-bc83-653ed58d41a3
INFO:__main__:Database connection acquired from pool successfully
INFO:__main__:âœ… Optimized database queries ready for use
INFO:__main__:âœ… Legacy integration modules connection updated
INFO:__main__:Loading code dictionaries asynchronously...
INFO:databricks.sql.auth.retry:Received status code 200 for POST request
INFO:databricks.sql.auth.thrift_http_client:HTTP Response with status code 200, message: OK
INFO:__main__:âœ… Loaded 182 codes from database:
INFO:__main__:   - entity_attribute: 29 codes
INFO:__main__:   - event_category: 67 codes
INFO:__main__:   - event_sub_category: 36 codes
INFO:__main__:   - relationship_direction: 2 codes
INFO:__main__:   - relationship_type: 48 codes
INFO:__main__:   Risk codes: 68 â†’ 68 (+0 from DB)
INFO:__main__:   PEP codes: 19 â†’ 19 (+0 from DB)
INFO:__main__:   Added 1 missing risk codes from debug analysis
INFO:__main__:ðŸ”„ Merged database codes with existing dictionaries
INFO:__main__:Code dictionaries loaded asynchronously
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-141' coro=<create_search_interface.<locals>.update_connection_status() done, defined at /Users/mukhiyas/Library/CloudStorage/OneDrive-moodys.com/Desktop/gr5-master/main.py:9023> exception=AttributeError("can't set attribute")>
Traceback (most recent call last):
  File "/Users/mukhiyas/Library/CloudStorage/OneDrive-moodys.com/Desktop/gr5-master/main.py", line 9029, in update_connection_status
    connection_status.classes = 'text-xs text-green-600 mt-2'
AttributeError: can't set attribute
